### ISSUE TITLE
Bug: unable to access or refresh /dashboard route after login

### ISSUE THREAD

**Issue by theperiscope** [dicedtomatoreal/typex#388] opened 2023-04-29 15:36 UTC
### What happened?

Environment:
  - Zipline 3.7.0 running in docker with "/" instead of "go" for URLs

Steps to reproduce:

1. Login as administrator, will redirect to /dashboard
2. refresh /dashboard page using F5 (fails, renders infinitely "..." and loading forever)
3. refresh /dashboard by accessing directly the route while logged in (fails, renders infinitely "..." and loading forever)
4. access /dashboard/urls (this works fine)
5. access /auth/login?url=/dashboard (this also works fine and redirects to dashboard)

### Version

upstream (ghcr.io/diced/zipline:trunk)

**Comment by diced** [comment] 2023-04-30 22:36
I have set the URLS_ROUTE to `/` like you have, and I am unable to reproduce this. Sending Zipline's logs and your browsers logs may be of help here.

**Comment by theperiscope** [comment] 2023-05-01 16:33
I'll try to gather the logs, including `DEBUG=true` and provide an update.

Meanwhile, another detail:

* I unintentionally omitted earlier that the Zipline instance is behind Caddy reverse proxy -- I think it has something to do with it as swtiching `/` to `/go` eliminates the issue, yet using `/` configuration directly (via IP address and port) did not produce the issue.

**Comment by diced** [comment] 2023-05-06 17:13
Interesting... I haven't used Caddy at all so I'm unsure, though I would expect it to behave the same as if it wasn't behind a reverse proxy.

**Comment by TacticalTechJay** [comment] 2023-05-10 05:55
Seems like this issue is *not present* in `:trunk`. So I suggest trying `ghcr.io/diced/zipline:trunk` for the image. Also, in your issue you indicated that you used upstream *and* latest (3.7.0) which may have caused some confusion for @diced. In the future, try to specify either version but not both.

After switching to `:trunk`, do provide an update so either me or @diced know whether to keep this issue open.

**Comment by TacticalTechJay** [comment] 2023-05-10 06:16
If you encounter an error like #397 when using `:trunk`, I've opened a PR (#401) that should fix it.

**Comment by diced** [comment] 2023-05-13 06:17
Closing for now, if the error still happens feel free to reopen or express concern within the issue here.

**Closed as completed by diced** 2023-05-13 06:17 UTC
Labels: bug

**Comment by theperiscope** [comment] 2023-05-14 14:24
Thanks, switching to `:trunk` resolved the dashboard refresh and now there is no issue refreshing with `/` as the URLS_ROUTE.

I think it is perhaps rewrite/redirect related to Next.js because earlier accessing indirectly via `https://example.com/auth/login?url=/dashboard` caused dashboard to refresh.
