### ISSUE TITLE
Bug: Invalid date on folders

### ISSUE THREAD

**Issue by wraithy** [dicedtomatoreal/typex#410] opened 2023-05-18 00:41 UTC
### What happened?

The "creation date" and "last updated" dates show as "invalid date" on the list view and "NaN years ago" in the grid view.

### List View
![image](https://github.com/diced/zipline/assets/83000298/201e2b6b-89f0-4545-97e9-730400f639ed)

### Grid View
![image](https://github.com/diced/zipline/assets/83000298/28041138-bccf-4f0e-8cb2-ee63ab651837)

### Version

upstream (ghcr.io/diced/zipline:trunk)

**Comment by TacticalTechJay** [comment] 2023-05-18 15:17
Try `ghcr.io/diced/zipline:trunk` for the docker image if you're using `ghcr.io/diced/zipline` or `ghcr.io/diced/zipline:latest`. It may already be fixed in the recommended image.

**Comment by wraithy** [comment] 2023-05-19 01:24
> Try `ghcr.io/diced/zipline:trunk` for the docker image if you're using `ghcr.io/diced/zipline` or `ghcr.io/diced/zipline:latest`. It may already be fixed in the recommended image.

I switched my docker image to `ghcr.io/diced/zipline:trunk` yesterday and I get the same thing (even when making new folders).

**Comment by TacticalTechJay** [comment] 2023-05-25 17:54
Do the folders have a valid date when checking with the database? If you're using postgres with docker, you can use this:
`docker compose exec postgres psql -U postgres -d postgres -c "SELECT * FROM \"Folder\";"`

**Comment by TacticalTechJay** [comment] 2023-05-25 17:58
Alternatively, you can use the API to check the date. You can either use curl with your token in the header or use the browser you're logged into zipline on. The endpoint is `/api/user/folders`

**Comment by wraithy** [comment] 2023-05-25 18:18
> Alternatively, you can use the API to check the date. You can either use curl with your token in the header or use the browser you're logged into zipline on. The endpoint is `/api/user/folders`

Looks like they do have valid dates when checking the database.

![image](https://github.com/diced/zipline/assets/83000298/1b2d7927-ee69-4113-8c53-de071dce1b58)

EDIT: Actually I think the issue is that they are not whole seconds and have a decimal at the end which is resulting in it being an invalid date.

**Comment by TacticalTechJay** [comment] 2023-05-25 18:34
Hmmm, it could be. How is `/api/user/folders`? Does it show the right date?

**Comment by wraithy** [comment] 2023-05-25 19:11
> Hmmm, it could be. How is `/api/user/folders`? Does it show the right date?

Dates look good to me via the endpoint

![image](https://github.com/diced/zipline/assets/83000298/c47c7e38-a928-4b5d-a77c-266f75a542f6)

**Comment by wraithy** [comment] 2023-05-25 20:54
I also tried removing the decimal and the numbers after in the database however they are just set to 0 when I fetch the info from the API.

![image](https://github.com/diced/zipline/assets/83000298/379da159-5647-4378-accd-fa6d19424d00)

**Comment by TacticalTechJay** [comment] 2023-07-22 02:25
Honestly got no clue what's causing this 😔
What browser @wraithdotcat? ~~And is the issue still happening~~

**Comment by wraithy** [comment] 2023-07-22 02:42
> Honestly got no clue what's causing this 😔 What browser @wraithdotcat? ~And is the issue still happening~

I am using Chrome and yea it is still happening :/

**Comment by TacticalTechJay** [comment] 2023-07-22 02:52
What version?

**Comment by wraithy** [comment] 2023-07-22 03:11
Trunk although I am using my fork (which is exactly the same just without the video thumbnails)

**Comment by TacticalTechJay** [comment] 2023-07-22 03:11
Chrome version?

**Comment by wraithy** [comment] 2023-07-22 03:13
Version 115.0.5790.102 (Official Build) (64-bit)

**Comment by TacticalTechJay** [comment] 2023-07-22 18:41
Do you currently use any extensions like an adblocker?

**Comment by wraithy** [comment] 2023-07-23 02:56
I do however I have tried other browsers and running in incognito and I get the same result

**Comment by diced** [comment] 2023-07-23 05:33
If you don't mind me asking, what country do you live in? If you are able to get the locale it could help us see if the problem is with your locale's way of parsing dates.

**Comment by wraithy** [comment] 2023-07-23 05:38
> If you don't mind me asking, what country do you live in? If you are able to get the locale it could help us see if the problem is with your locale's way of parsing dates.

I live in the UK however my instance is hosted in Ashburn, Virginia in the US. I assume that the times are based on the server time rather than the client but I could be wrong so I thought I would include both.

**Comment by TacticalTechJay** [comment] 2023-07-26 18:47
Seems like that was it. Doesn't seem to enjoy other format for time

**Comment by TacticalTechJay** [comment] 2023-07-26 18:47
@diced 🫡

**Comment by diced** [comment] 2023-07-26 22:09
hopefully the commit above fixes this issue for good, but i'll still leave this issue open until we hear back from @wraithdotcat

**Comment by wraithy** [comment] 2023-07-27 05:50
The dates are fixed now thanks!

![image](https://github.com/diced/zipline/assets/83000298/949626c6-bda5-4101-9949-43130e910984)

however now the images don't load :/

![image](https://github.com/diced/zipline/assets/83000298/1d5db2ed-3ba1-43da-85ac-34e62afd4aa1)

the image source is `domain.tld/r/image.png?compress=false` and when I go directly to that url I get the following

`{"statusCode":500,"code":"ENOENT","error":"Internal Server Error","message":"ENOENT: no such file or directory, open './mimes.json'"}`

**Comment by TacticalTechJay** [comment] 2023-07-27 06:46
Doesn't seem to have been caused by me `¯\_(ツ)_/¯`
@diced I think you managed to exclude mimes.json from the docker image somewhere down the line...

**Comment by TacticalTechJay** [comment] 2023-07-27 06:48
So, with the issue at the beginning resolved I'll be closing this. Open a new one with your new problem for organization purposes.

**Closed as completed by TacticalTechJay** 2023-07-27 06:48 UTC
Labels: bug
