### ISSUE TITLE
Bug: You can't modify administrators as a super admin

### ISSUE THREAD

**Issue by RappyTV** [dicedtomatoreal/typex#526] opened 2024-01-09 09:07 UTC
### What happened?

I tried removing admin privileges of another admin and it wouldn't let me even though I am the superuser.
![image](https://github.com/diced/zipline/assets/72705182/e4e41357-1a0d-4b8d-b50e-2fc35ac7a527)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by iiTranquility** [comment] 2024-01-09 21:35
I just changed a user to admin and back on 3.7.8 and it let me do that without any errors.
Not sure why yours is doing that.

**Comment by RappyTV** [comment] 2024-01-10 08:19
weird, 'cause i'm on 3.7.8 too xd

**Comment by diced** [comment] 2024-01-19 20:30
I'm not able to reproduce this, I'll be closing the issue but if the issue is still there try using the `trunk` tag as the `latest` and `trunk` tag are a bit out of sync right now.

**Closed as completed by diced** 2024-01-19 20:30 UTC
Labels: bug
