### ISSUE TITLE
Bug: Imported files show no size

### ISSUE THREAD

**Issue by respektive** [dicedtomatoreal/typex#468] opened 2023-09-30 17:07 UTC
### What happened?

When importing files via the import script, they all show 0.0B as the size in the dashboard. The total storage stats show the correct total size. The logs don't seem to have anything useful.

![](https://pek.li/MoD9dq.png)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox

### Zipline Logs

```shell
2023-09-30 05:00:21,443 PM info  [datasource] using Local(./uploads) datasource
Imported konata4.png (image/png mimetype) to user 4
Imported legogar.png (image/png mimetype) to user 4
Imported test.txt (text/plain mimetype) to user 4
2023-09-30 05:00:21,451 PM info  [database::migrations] establishing database connection
2023-09-30 05:00:21,451 PM info  [database::migrations] ensuring database exists, if not creating database - may error if no permissions
2023-09-30 05:00:21,578 PM info  [database::migrations] exiting migrations engine - database is up to date
Starting transaction to database..
Finished transaction to database.
Copying files to local storage..
Finished copying files to local storage.
```

**Comment by TacticalTechJay** [comment] 2023-10-01 00:23
Not a bug. It is, however, a bit dated since it doesn't include a file's size.

**Comment by diced** [comment] 2023-11-06 05:56
fixed in https://github.com/diced/zipline/commit/89c58044a3fa12330c49034e081b26a030c4af2c
imported files will now have size associated

**Closed as completed by diced** 2023-11-06 05:56 UTC
Labels: bug
