### ISSUE TITLE
Bug: Refreshing stats page throws error

### ISSUE THREAD

**Issue by RappyTV** [dicedtomatoreal/typex#340] opened 2023-03-23 11:13 UTC
### What happened?

When I refresh the `stats` page this happens:

https://user-images.githubusercontent.com/72705182/227186515-3b2c40a7-3134-4b21-a016-7994ac487038.mp4

Just navigating to the page works.

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment] 2023-03-23 13:52
Provide server and/or browser logs please.

**Comment by RappyTV** [comment] 2023-03-23 15:24
![image](https://user-images.githubusercontent.com/72705182/227251954-bec0c3e0-a35c-4c28-ab61-b39f333759ae.png)

**Comment by diced** [comment] 2023-03-24 23:55
Seems like the error may have something to with hooks being rendered incorrectly. Unfortunately I can't reproduce it while in development mode so any fix may not work.

**Comment by diced** [comment] 2023-03-25 00:00
Ah, nevermind. This issue persists within versions before 3.7.0's RCs (it was fixed in one of the 3.7.0 RC's). Please make sure when making an issue you select the correct version, as you have selected "upstream" instead of stable.

**Closed as completed by diced** 2023-03-25 00:00 UTC
Labels: bug
