### ISSUE TITLE
Error report, multible videos uploaded at same time crashes zipline service

### ISSUE THREAD

**Issue by superintendent2521** [dicedtomatoreal/typex#159] opened 2022-07-08 01:07 UTC
if you ever use zipline as a sharex image host and try to upload 2 mp4 files at the same time, it will end up crashing your entire server,

**Comment by superintendent2521** [comment] 2022-07-08 01:10
how to reproduce:
Have 2 Mp4 files
Upload both of them at the same time
And watch it crash and burn

**Comment by NebulaBC** [comment] 2022-07-08 01:38
Please try to use more descriptive names for bug reports. One example could be: Uploading multiple files at once crashes server.
you could also check if an error is sent in console.

**Comment by diced** [comment] 2022-07-08 02:30
Not able to reproduce with the given details, I need the file size of both videos to look into this issue. Consider renaming the issue like the comment above.

**Comment by superintendent2521** [comment] 2022-07-10 04:09
how to reproduce, take 2 mp4 files of 40 to 41 mb size and try to upload both of them at the same time using the upload feature on the website, not sharex the website, and if you try to refresh you will get a 521 on cloudflare If you use cloudflare, which i do

**Comment by superintendent2521** [comment] 2022-07-10 04:10
Msg to repopen

**Comment by diced** [comment] 2022-07-10 05:14
Are there any logs in zipline after uploading these files? Also keep this issue open.

**Comment by superintendent2521** [comment] 2022-07-10 15:41
Why does this keep closing, Also i need to check the logs, how would i do that

**Comment by diced** [comment] 2022-07-10 18:49
> Why does this keep closing

Don't click the not-green button that says "Close with comment", instead click on the green button which just says "Comment".

> Also i need to check the logs, how would i do that

If you are using docker/docker-compose head over to the directory where zipline is and run `docker-compose logs zipline` and copy it over here (preferably the entire thing, unless you know what to send over)

**Comment by diced** [comment] 2022-07-10 19:54
While we are getting more information on this, could you also list your servers specs like its RAM, CPU, Operating System, etc?

**Comment by superintendent2521** [comment] 2022-07-10 22:39
The operating system is ubuntu 20.04  it has 1 vcore and has 1gb of ram, it seems to be running very well as its handeling about 5 people every once and awhile

**Comment by superintendent2521** [comment] 2022-07-10 23:23
the logs are this right here
https://www.toptal.com/developers/hastebin/unedohabep.properties
it seems to have outputted alot of randomness of which i cant read, it seems to be some errors inside of the logs

**Comment by diced** [comment] 2022-07-11 00:53
I'm not seeing anything where you upload a video, could you upload a video then upload the logs over here? Thanks

**Comment by superintendent2521** [comment] 2022-07-11 00:58
Yes. i will. i will comment the new information after i test this

**Comment by superintendent2521** [comment] 2022-07-11 01:00
weird. seems to have not happend this time. maybe it was a one off issue?

**Comment by diced** [comment] 2022-07-11 01:02
I will close this issue, but if it happens again feel free to open it and send the logs again.

**Closed as not planned** 2022-07-11 01:02 UTC
