### ISSUE TITLE
Bug: v4 Docker Image fails to start since yesterday

### ISSUE THREAD

**Issue by BeSlightly** [dicedtomatoreal/typex#608] opened 2024-09-14 02:07 UTC
### What happened?

Since 96a6fe5 the v4 docker container won't start on my ARM system anymore. (Error in Zipline logs)
The same error also occurs on the latest build that was pushed earlier today.

Returning to [v4-db28b06-arm64](https://github.com/users/diced/packages/container/zipline/263233214?tag=v4-db28b06-arm64) makes the container start normally again.

### Version

other (provide version in additional info)

### Zipline Logs

```shell
zipline     | /zipline/build/server/index.js:12
zipline     | var dotProp = require('dot-prop');
zipline     |               ^
zipline     | 
zipline     | Error [ERR_REQUIRE_ESM]: require() of ES Module /zipline/node_modules/.pnpm/dot-prop@9.0.0/node_modules/dot-prop/index.js from /zipline/build/server/index.js not supported.
zipline     | Instead change the require of /zipline/node_modules/.pnpm/dot-prop@9.0.0/node_modules/dot-prop/index.js in /zipline/build/server/index.js to a dynamic import() which is available in all CommonJS modules.
zipline     |     at Object.<anonymous> (/zipline/build/server/index.js:12:15) {
zipline     |   code: 'ERR_REQUIRE_ESM'
zipline     | }
zipline     | 
zipline     | Node.js v18.16.0
zipline exited with code 0
```

**Comment by diced** [comment] 2024-09-14 02:59
I'm not sure I understand, since the v4-db28b06-arm64 tag shouldn't even produce an error like this (dot-prop is only used in recent commits)

Another thing, I had arm64 builds not working for a while since my runner was offline but I have started it up again since yesterday so any images with the `v4` tag should work on arm, and I would advise you to pull the v4 tag again and see if you run into this error. 

Some more information, the database schema has changed a lot since that commit and you might have to run the `pnpm db:prototype` command again, like you did in the first run (Hopefully)

**Comment by BeSlightly** [comment] 2024-09-14 03:58
Aye, my wording might have been poor, sorry.
The error does not occur on  v4-db28b06-arm64, instead this is the last arm build that works for me.

Since yesterday's update the dot-prop error pops up and today's update sadly didn't change it either - it's still happening.

**Comment by diced** [comment] 2024-09-14 04:17
Yeah, sorry about that, I read your description wrong- the issue is just dot-prop doesn't support CommonJS at all which seems pretty stupid, so I've just reimplemented it and simplified it so it's no longer needed. 

Fixed in https://github.com/diced/zipline/commit/7eb45758c82ea5ce05a54394f1ad1e686de5b151 along with some other bugs I caught while testing. Hopefully this works!

**Closed as completed by diced** 2024-09-14 04:17 UTC
Labels: bug, v4
